# Generated by Django 4.1.6 on 2023-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='Description',
            field=models.TextField(default=True, max_length=250),
        ),
    ]
