# Generated by Django 4.1.6 on 2023-02-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='email_id',
        ),
    ]
